### PR TITLE
Update worlddata.xml

### PR DESCRIPTION
**Pull request by ghost**
Reworked <starcolor> to reflect known astronomy. I updated the percentages to include additional types, although the % doesnt match actual recorded frequency of stellar types.

### CODE REVIEW

**Comment by morgajel** [comment]
While I like the improved color spectrum matching astronomy conventions, I'm not 100% sure on including the type. Take the following example:

_Venketry orbits a binary star: Aban, an average yellow star and Lux, a large brown star._
becomes
_Venketry orbits a binary star: Aban, an average type F yellow star and Lux, a large type T brown star._

Perhaps changing it from "a large type T brown star" to "a large brown (type T) star" would flow better? I don't know how including the astronomical type would be useful in the campaign :/

As to the recorded frequency of stellar types, you have to skew it for habitable planets (which is 100% completely made up, I admit) :)

**Comment by ghost** [comment]
No worries jesse. We can just remove the type :)

**Comment by morgajel** [comment]
When you get a chance, make that tweak and I'll merge it :)

**Comment by ghost** [comment]
Will do :) away from home atm.

**Comment by ghost** [comment]
Im not sure how to alter a pull request. Looked through Help and couldnt
find it. Any clues?

On Fri, Dec 6, 2013 at 7:31 PM, Jesse Morgan notifications@github.comwrote:

> When you get a chance, make that tweak and I'll merge it :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CityGenerator/CityGenerator/pull/225#issuecomment-30022089
> .

## 

Ian Liddle
Treasurer, Desborough Royal British Legion
Deputy Poppy Appeal Organiser, Desborough

**Comment by morgajel** [comment]
I'll close out this request, then simply submit a new one.

**Pull request closed without merging**
